### ISSUE TITLE
about returns_17_10.csv

### ISSUE THREAD

**Issue by heyangdev** [xixi0222/Black-Litterman-Model#1]
Hello, thanks for your open your project, and I get a problom when I run BLM.py, because I can't find returns_17_10.csv which is needed by  BLM.py. Could you seed it to me, thank you very much.

**Comment by heyangdev** [comment]
@xixi0222

**Comment by xixi0222** [comment]
Hi,


I have uploaded all data files on the directory called code. And I do not have the file BLM.py.





-----Original Messages-----

**Comment by heyangdev** [comment]
I want the returns_17_10.csv, not BLM.py.

**Comment by xixi0222** [comment]
Please see my code structure again, I think you are not using my code.


-----Original Messages-----

**Comment by heyangdev** [comment]
ok, think you！
